# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        repository: 'tea'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
    - task: CmdLine@2
      inputs:
        script: 'docker image ls'
    - task: ECRPushImage@1
      inputs:
        awsCredentials: 'aws-demo'
        regionName: 'us-east-1'
        imageSource: 'imagename'
        sourceImageName: 'tea'
        sourceImageTag: '$(tag)'
        repositoryName: 'tea'
        pushTag: '$(tag)'