# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DockerInstaller@0
      inputs:
        dockerVersion: '20.10.0'
    - task: AWSShellScript@1
      inputs:
        awsCredentials: 'aws-demo'
        regionName: 'us-east-1'
        scriptType: 'inline'
        inlineScript: 'echo "loggin in to ECR" && aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin "004889159502.dkr.ecr.us-east-1.amazonaws.com/tea"'
    - task: CmdLine@2
      inputs:
        script: 'docker buildx create --name multiarch && docker buildx use multiarch && docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t "004889159502.dkr.ecr.us-east-1.amazonaws.com/tea":$(tag) . --push'
- stage: Deploy
  displayName: Deploy to EKS
  dependsOn: Build
  jobs:
    - job: Deploy
      displayName: 'Deploying SVC to EKS'
      pool:
        vmImage: 'ubuntu-latest'
        
      steps:
      - task: KubernetesManifest@0
        inputs:
          action: 'deploy'
          kubernetesServiceConnection: 'aws-eks-dev'
          namespace: 'default'
          manifests: 'deployment.yaml'
          containers: '004889159502.dkr.ecr.us-east-1.amazonaws.com/tea:$(tag)'
